baseURL = "https://fushigi.netlify.app/"
theme = "risotto"
title = "Fushigi"
author = "Zach Quita"
copyright = "© [Fushigi](/) site by [Zach Quita](https://www.youtube.com/watch?v=3Xdo0MVZcSo)"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
#palette = ""
#palette = "black-metal-venom"
palette = "gruvbox-light"

#Sidebar: about/bio
[params.about]
title = "~/ Fushigi"
description = "A home for my thoughts, projects, and my current interests."
#logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Zakar98k"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:zachquita@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/zakar98k/"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
